### ISSUE TITLE
Составить спецификацию

### ISSUE THREAD

**Issue by owlengineer** [DarkFlink/VKFriends#1]
Продумать и прописать конкретные детали проекта, т.е. что должно получиться в итоге. Общая тема - визуализатор друзей пользователя в VK. Нужно придумать:
- [x] Как программа будет выводить список друзей какого-то пользователя, например в виде суффиксного дерева или как-то ещё, написать их сюда **(Всем)**
- [x] Что ещё она должна уметь, например выводить помимо фото в вершине графа информацию, придумать несколько идей, написать их сюда **(Всем)**
- [x] Вид GUI, как примерно это будет выглядеть, т.е какие инструменты (кнопки, тулбары и т.д) должны выполнять какие функции, например, добавить аккаунт в граф (граф перестраивается, согласно списку друзей), удалить аккаунт из графа и т.д. На выходе, скрин наброска GUI **(Андрей)**
- [x] Разобраться, как работает API вконтакте. На выходе получить демку, которая по http запросу к вк получает список друзей определённого пользователя, например по ID **(Слава)**
- [x] Понять, как пишутся unit-тесты в java, что для этого нужно. Возможно, использовать инструменты IDE, или какие-то библиотеки. На выходе, написать unit-test для какой-нибудь простой функции или набора функций, который скажет, проходит ли она все тесты. **(Амир)**
- [x] Перевести ридми на русский
- [x] Добавить план разработки в ридми

Deadline - 4 июля 2019

**Comment by AndrewGavril** [comment]
1) Суффиксное дерево, если граф - это только список друзей указанного пользователя, если будем делать реализацию поиска пути через друзей у 2х пользователей, то связный граф.
2) Можно попробовать реализацию пересылки на страницу браузера, при нажатии на человека (либо на страницу пользователя, либо на страницу диалога с этим пользователем).
