### ISSUE TITLE
Спецификация в ReadMe отсутствует или не соответствует требованиям

### ISSUE THREAD

**Issue by makometr** [DarkFlink/VKFriends#18]
- [x] формальная постановка задачи
- [x] алгоритм
- [x] требуемые структуры данных (свойства полученного графа)
- [x] описание формата входных и выходных данных (откуда берутся данные, в каком формате, какие данные/файлы получаем на выходе и в каком формате)
- [x] примерное описание GUI
- [x] + исправить описание (рёбро, Оно строит граф -> в процессе работы строится граф, ...)
- [x] добавьте в роли ещё как минимум отчёт

**Comment by AndrewGavril** [comment]
Добавлена графа с спецификацией структур данных, и графа с описанием входных/выходных данных. Добавлен скриншот с примерным видом GUI. Исправлено описание и добавлена роль.
