### ISSUE TITLE
Сделать демо GUI

### ISSUE THREAD

**Issue by owlengineer** [DarkFlink/VKFriends#2]
Вид GUI, как примерно это будет выглядеть, т.е какие инструменты (кнопки, тулбары и т.д) должны выполнять какие функции, например, добавить аккаунт в граф (граф перестраивается, согласно списку друзей), удалить аккаунт из графа и т.д. На выходе, скрин наброска GUI и отдельная ветка с этим GUI

**Comment by AndrewGavril** [comment]
Добавить минимальный размер окна

**Comment by AndrewGavril** [comment]
![Uploading Снимок экрана от 2019-07-03 23-10-52.png…]()

**Comment by Gizzatovamir** [comment]
![Gui_test](https://user-images.githubusercontent.com/31562121/60655753-fe293400-9e56-11e9-851f-f346f83b846c.png)
