### ISSUE TITLE
Разобраться как пишутся unit-тесты

### ISSUE THREAD

**Issue by owlengineer** [DarkFlink/VKFriends#4]
Понять, как пишутся unit-тесты в java, что для этого нужно. Возможно, использовать инструменты IDE, или какие-то библиотеки. На выходе, написать unit-test для какой-нибудь простой функции или набора функций, который скажет, проходит ли она все тесты.

**Comment by Gizzatovamir** [comment]
![unknown](https://user-images.githubusercontent.com/31562121/60623791-2d568b80-9dec-11e9-9414-0eb219400435.png)
