### ISSUE TITLE
Протестировать getCommonFriends

### ISSUE THREAD

**Issue by owlengineer** [DarkFlink/VKFriends#44]
- [x] Найти и написать сюда случаи, когда метод работает криво
- [x] Написать юнит-тест для метода getCommonFriends

**Comment by Gizzatovamir** [comment]
как мне протестировать метод если он не замержен?

**Comment by Gizzatovamir** [comment]
потому что idea не хочет копировать с не локальной ветки

**Comment by AndrewGavril** [comment]
Обнови репу, перейди на ветку с PR

**Comment by Gizzatovamir** [comment]
Map требует в виде аргументов ссылки, а не примитивные типы данных

**Comment by Gizzatovamir** [comment]
мне изменить их?

**Comment by Gizzatovamir** [comment]
![image](https://user-images.githubusercontent.com/31562121/60969299-e3a7fc80-a327-11e9-9157-b8a68a35a3d0.png)

**Comment by Gizzatovamir** [comment]
> * [ ]  Написать юнит-тест для метода getCommonFriends

метод не рабочий
